name: experthub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Italic.ttf
        - asset: assets/fonts/Kanit/Kanit-Thin.ttf
        - asset: assets/fonts/Kanit/Kanit-Light.ttf
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf